### ISSUE TITLE
PolicyRule Serializer - Zone field appears to use incorrect serializer

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot-plugin-firewall-models#136]
### Environment
* Python version:   NA
* Nautobot version:   1.5.10
* nautobot-plugin-firewall-model version:   1.1.X & 1.2.0

### Expected Behavior
UUID should be able to be used for API when adding a zone to a policy rule

### Observed Behavior
Requires full zone payload

### Steps to Reproduce
1.
2.
3.

**Comment by Cymmus** [comment]
I have the same problem.

Easy to fix i think. Need to change the Serializer in api/serializers line 230 in class PolicyRuleSerializer.

Change:
 source_zone = ZoneSerializer(required=False)

With:
     source_zone = SerializedPKRelatedField(
        queryset=models.Zone.objects.all(), serializer=ZoneSerializer, required=False
    )
    
   and same thing for the destination zone line 240.

**Comment by whitej6** [comment]
Resolved by #146
