### ISSUE TITLE
Unable to filter policy rules by name

### ISSUE THREAD

**Issue by gneville-ot** [nautobot/nautobot-plugin-firewall-models#145]
### Environment
* Python version:  3.10
* Nautobot version:  1.5.16
* nautobot-plugin-firewall-model version:  1.2.0

Either via the GUI or RestAPI be able to filter policy-rules by their name

The filter is not valid

### Steps to Reproduce
1. Browse to policy-rules
2. Click filter and use the name field and try to filter with a valid name

**Comment by whitej6** [comment]
Resolved by #146
