### ISSUE TITLE
Add default formula for policy rule name to the policy rule selection dropdown for policies

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot-plugin-firewall-models#52]
### Environment
* Nautobot version:  1.3.5
* nautobot-plugin-firewall-model version:  7c914f7f703200909c6cd045e7e681b8dbf8967a

### Proposed Functionality
When selecting policy rules for a given policy, instead of showing a blank selectable item, generate a default name (real-time, not to be saved to the database) to display.

### Use Case
Policy rules are very hard to select if they lack a name.

![Screenshot 2022-07-07 at 09 13 59](https://user-images.githubusercontent.com/12400533/177714015-429ea8ae-423e-48ed-a505-2c820a736a7e.png)

![Screenshot 2022-07-07 at 09 14 17](https://user-images.githubusercontent.com/12400533/177714053-f5ed1e2c-fb9e-42b1-87e1-bacf0f33fb09.png)

**Comment by Kircheneer** [comment]
@whitej6 this is done as per 85a569f?

**Comment by whitej6** [comment]
Yes
