### ISSUE TITLE
Allow Weight to be defined via UI

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot-plugin-firewall-models#66]
### Environment
* Nautobot version:  1.3
* nautobot-plugin-firewall-model version:  0.1

### Proposed Functionality

Allow the ability to configure the weight of a policy via the UI.

### Use Case

To make it clear which order Policies should be applied in. Consider the following:

* A Policy Deny-Bogons is assigned to device=nyc-fw01 and defaults to weight 1000
* A PolicyAllow-Internet is assigned to device=nyc-fw01 and defaults to weight 1000

The default algorithm (or lack thereof) orders them in the wrong order as one would expect. Yes they can adjust it via the API, but many will not be aware of that.

**Comment by Kircheneer** [comment]
If I'm seeing this correctly this functionality is available through the "Edit Policy Weight On Assigned Device" tab under the policy detail page (e.g. `/plugins/firewall/policy/0320321a-b924-4c27-8faa-af044cb7d62e/?tab=edit-policy-device-weight`)
