### ISSUE TITLE
PolicyRules relationship change from M2M to ForeignKey

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot-plugin-firewall-models#67]
### Environment
* Nautobot version:  1.3
* nautobot-plugin-firewall-model version:  0.1

### Proposed Functionality

The ability to more closely align PolicyRules to the Parent Policy. While it is clear that the current design is more flexible, that flexibility comes at the cost of complexity (both in code, mind mapping, and UI) vs the ForeignKey approach. 

### Use Case

* Easy viewing when viewing PolicyRules, which Policy it is applied to
* Easy viewing when viewing Policy, which PolicyRules it is applied to
* Easier ability to find a rule (e.g. filtering via Policy)
* More closely aligning to how rules are maintained in every firewall system I am aware of Palo Alto, ASA, Juniper SRX, Juniper Netscreen.
* More closely aligning to domain managers I am aware of where they will have a construct like Panorama does where Device Group == Policy, a Policy has rules, and Policy can be applied to multiple devices. Similar for Panorama, Fortimanger, Juniper NSM, and Juniper Space.

**Comment by whitej6** [comment]
- Should the FK be a required field? (create policy first)
- The weight would switch to being on the PR model not the through model
- Clone to make up for the loss of reuse of PRs?

**Comment by itdependsnetworks** [comment]
1/3 yes
2 first weight or index? For weight I would have thought on the policy model, but I suspect you have thought of that and it doesn’t work out.

**Comment by itdependsnetworks** [comment]
yea, index to PolicyRule

**Comment by whitej6** [comment]
Resolved by #80
