### ISSUE TITLE
Readthedocs out of date

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot-plugin-firewall-models#76]
### Environment
* Python version:  
* Nautobot version:  
* nautobot-plugin-firewall-model version:  v0.1.0-beta.3 

### Expected Behavior

Readthedocs documentation up to date

### Observed Behavior

Docs in https://nautobot-plugin-firewall-models.readthedocs.io/en/latest/ look out of date

### Steps to Reproduce
1.
2.
3.

**Comment by whitej6** [comment]
This appears to be resolved. Possibly due to previous were pre-release?
