### ISSUE TITLE
`create_status` in `0002_custom_status.py` adds too many models to the content types for the applicable Statuses

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot-plugin-firewall-models#86]
### Environment
* Python version:  3.8.13
* Nautobot version: 1.4.1
* nautobot-plugin-firewall-model version: 1.0.1

### Expected Behavior
`create_status` in `0002_custom_status.py` only adds models that need a status to the content types for the applicable Statuses. I'm not sure how big of a problem this is in practice but I thought I'd report it. If this is intended, please let me know why so I can understand it better.

### Observed Behavior
`create_status` in `0002_custom_status.py` adds all the M2M through models to the content types for the applicable Statuses.

### Steps to Reproduce
1. `$ inv build start nbshell`
2. `>>> list(Status.objects.get(name="Active").content_types.all())`

**Comment by smk4664** [comment]
I would like to take this one.
